### ISSUE TITLE
node-sass multiple importers 

### ISSUE THREAD

**Issue by dreerr** [marcofugaro/gulp-frontend-boilerplate#1]
Does the part with importers in your `styles.js` work?
`importer: [moduleImporter(), globImporter()]`
throws an error for globbing whereas
`importer: [globImporter(), moduleImporter()]`
throws an error for a missing module

any idea how to fix this?

**Comment by marcofugaro** [comment]
Fixed, apparently ~~you're supposed to not call the functions when you import them in an array~~, like this:

``` js
importer: [globImporter, moduleImporter]
```

Thanks for the heads up!

EDIT: Nope, I'm wrong

**Comment by dreerr** [comment]
Does not work, now it is just failing silently. Just tried with your bp as well.

**Comment by marcofugaro** [comment]
Yup you were right, i dug inside the importers and basically they weren't  made to work with other importers, I didn't know how to fix it so I submitted an issue to the Importers repo.

In the meantime you could use [gulp-sass-glob](https://github.com/tomgrooffer/gulp-sass-glob) with sass-module-importer being the only importer, that works!

**Comment by marcofugaro** [comment]
Closing since now we're not using `globImporter()` anymore in favor of [gulp-sass-glob](https://github.com/tomgrooffer/gulp-sass-glob) definitively. The pipeline now works.
